from fireo import models


class ChatSession(models.Model):
    """
    Represents a single chat conversation.
    Each user can have multiple sessions (chats).
    """
    user_uid    = models.TextField(required=True)
    title       = models.TextField(required=False, default="New Chat")
    created_at  = models.DateTime(auto=True)
    updated_at  = models.DateTime(required=False)

    class Meta:
        collection_name = "chat_sessions"

    def to_dict(self):
        return {
            "chat_id":    self.id,
            "user_uid":   self.user_uid,
            "title":      self.title,
            "created_at": str(self.created_at) if self.created_at else None,
            "updated_at": str(self.updated_at) if self.updated_at else None,
        }


class Message(models.Model):
    """
    Represents a single message inside a ChatSession.
    role = 'user'      → message sent by the user
    role = 'assistant' → reply generated by the AI
    Both are always saved to DB as a pair after each exchange.
    """
    chat_id    = models.TextField(required=True)   # FK → ChatSession.id
    user_uid   = models.TextField(required=True)
    role       = models.TextField(required=True)   # 'user' | 'assistant'
    content    = models.TextField(required=True)
    created_at = models.DateTime(auto=True)

    class Meta:
        collection_name = "chat_messages"

    def to_dict(self):
        return {
            "id":         self.id,
            "chat_id":    self.chat_id,
            "role":       self.role,
            "content":    self.content,
            "created_at": str(self.created_at) if self.created_at else None,
        }
